<?php

namespace WebManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * backEndRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class backEndRepository extends EntityRepository
{
}
