<?php

namespace WebManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * filesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class filesRepository extends EntityRepository
{
}
