<?php

namespace WebManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * linksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class linksRepository extends EntityRepository
{
}
