<?php

namespace WebManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * quote_emailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class quote_emailsRepository extends EntityRepository
{
}
