<?php

namespace WebManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * user_rolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user_rolesRepository extends EntityRepository
{
}
